# Fill the ETF CSV URLs and the CIK for TCI.
# If an ETF CSV URL is unknown, leave it blank for now.
managers:
  - id: GRNY
    name: Fundstrat Granny Shots ETF
    type: etf_html_table
    page_url: "https://grannyshots.com/holdings/"
    table_selector: "#holding-tables"         
    asof_selector: "p.time-stamp.pt-3"
  - id: MPLY
    name: Strategy Shares Monopoly ETF
    type: etf_csv
    csv_url: "https://strategysharesetfs.com/feeds/STRATEGYSHARES_STRATEGYSHARESMPLY_ETF_TOPHOLDINGS.CSV"
  - id: IVES
    name: Wedbush AI ETF (IVES)
    type: etf_csv
    csv_url: "https://wedbushfunds.com/latest-sod-holdings"
  - id: TCI
    name: The Children’s Investment Fund
    type: sec_13f
    cik: "0001647251"
